[openjanus]
# Set the listen key. You can use something like `f10` for the `f` keys, or just set a string to a key you want to press.
listen_key = "f10"
# The TTS engine to use, must be one of `whisper` or `elevenlabs`
tts_engine = "elevenlabs"
# The directory to store the recordings in, if it doesn't exist, we'll try to make it. Relative to working path.
recordings_directory = "recordings"

[openai]
# Set your openai api key here
api_key = "sk...."
# Set the path to `mpv.exe` if it's not already in your PATH. Only matters if `tts_engine` == `whisper`
# mpv_path = mpv.exe

[elevenlabs]
api_key = ""