[openjanus]
# Set the listen key. You can use something like `f10` for the `f` keys, or just set a string to a key you want to press.
listen_key = "f10"
# The TTS engine to use, must be one of `whisper` or `elevenlabs`
tts_engine = "elevenlabs"
# The directory to store the recordings in, if it doesn't exist, we'll try to make it. Relative to working path.
recordings_directory = "recordings"

[openai]
# Set your openai api key here
openai_api_key = "sk...."

[openai.whisper]
# Set the path to `mpv.exe` if it's not already in your PATH. Only matters if `tts_engine` == `whisper`
# mpv_path = mpv.exe
# Which openai whisper voice ID to use, defaults to "nova" if not set
whisper_voice_id = "nova"
# Which openai whisper engine ID to use, defaults to "tts-1" if not set
whisper_voice_model = "tts-1"
# Which openai whisper TTS engine to use, defaults to `whisper-1` if not set
whisper_engine = "whisper-1"

[elevenlabs]
eleven_api_key = ""
# If not set, it'll use the default voice
elevenlabs_voice_id = ""
# If not set it'll use the default stability (0.5)
elevenlabs_stability = 0.5
# If not set it'll use the default similarity_boost (0.75)
elevenlabs_similarity_boost = 0.75
# If not set it'll use the default style (0). You probably want this at zero
elevenlabs_style = 0
# If not set to "True" it'll use the default speaker_boost setting (False)
elevenlabs_use_speaker_boost="False"