[openjanus]
# Set the listen key. You can use something like `f12` for the `f` keys, or just set a string to a key you want to press.
listen_key = "f12"
# The TTS engine to use, must be one of `whisper` or `elevenlabs`
tts_engine = "elevenlabs"

[openai]
# Set your openai api key here
api_key = "sk...."
# Set the path to `mpv.exe` if it's not already in your PATH. Only matters if `tts_engine` == `whisper`
# mpv_path = mpv.exe

[elevenlabs]
api_key = ""